---
- name: Create kubernetes environment
  gather_facts: No
  hosts: all

  tasks:
    - name: Create a Deployment object
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          force: yes
          metadata:
            name: nginx-app
            namespace: default
            labels:
              app: nginx-app
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx-app
            template:
              metadata:
                labels:
                  app: nginx-app
              spec:
                containers:
                - name: nginx
                  image: rafa73/static_site:{{ IMAGE_TAG }}
                  ports:
                  - containerPort: 80


    - name: Create a Service object
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:  
            name: nginx-service
            namespace: default
          spec:
            selector:    
              app: nginx-app
            type: ClusterIP
            ports:  
            - name: http
              port: 80
              protocol: TCP


    - name: Create an Ingress object
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: nginx-ingress
            namespace: default
          spec:
            rules:
            - http:
                paths:
                - path: /
                  pathType: Prefix
                  defaultBackend:
                    service:
                      name: nginx-service
                      port:
                        number: 80

